#!/bin/sh
set -e
# Automatically added by dh_installmodules/13.20
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -e /boot/System.map-4.14.190-microsoft-epsilon ]; then
		depmod -a -F /boot/System.map-4.14.190-microsoft-epsilon 4.14.190-microsoft-epsilon || true
	fi
fi
# End automatically added section
